import type {Metadata} from "next";
import {Roboto, Geist_Mono} from "next/font/google";
import "./globals.css";
import React from "react";
import {ThemeProvider} from "next-themes";
import AuthProvider from "@/components/AuthProvider";


export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <AuthProvider>
            <html lang="en" suppressHydrationWarning={true}>
                <head>
                    <link
                        rel="stylesheet"
                        href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css"
                        integrity="sha384-n8MVd4RsNIU0tAv4ct0nTaAbDJwPJzDEaqSD1odI+WdtXRGWt2kTvGFasHpSy3SV"
                        crossOrigin="anonymous"
                    />
                </head>
                <body className={`${roboto.variable} ${geistMono.variable} antialiased`} suppressHydrationWarning={true}>
                      <ThemeProvider attribute="class"
                                     defaultTheme="system"
                                     enableSystem
                                     disableTransitionOnChange>
                          {children}
                      </ThemeProvider>
                </body>
            </html>
        </AuthProvider>
    );
}

const roboto = Roboto({
    variable: "--font-roboto",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "A Unique EduTech App",
    description: "Generated by create next app",
};
