import type {Metadata} from "next";
import {Geist_Mono, Noto_Sans_Bengali} from "next/font/google";
import "./globals.css";
import React from "react";
import {ThemeProvider} from "next-themes";
import AuthProvider from "@/components/AuthProvider";


export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <AuthProvider>
            <html lang="bn" suppressHydrationWarning={true}>
                <head>
                    <link rel="preconnect" href="https://cdn.jsdelivr.net" />
                    <link
                        rel="preload"
                        href="https://cdn.jsdelivr.net/gh/chaijax/kalpurush@main/Kalpurush.ttf"
                        as="font"
                        type="font/ttf"
                        crossOrigin="anonymous"
                    />
                    <link
                        rel="stylesheet"
                        href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css"
                        integrity="sha384-n8MVd4RsNIU0tAv4ct0nTaAbDJwPJzDEaqSD1odI+WdtXRGWt2kTvGFasHpSy3SV"
                        crossOrigin="anonymous"
                    />
                </head>
                <body className={`${notoSansBengali.variable} ${geistMono.variable} antialiased`} suppressHydrationWarning={true}>
                      <ThemeProvider attribute="class"
                                     defaultTheme="system"
                                     enableSystem
                                     disableTransitionOnChange>
                          {children}
                      </ThemeProvider>
                </body>
            </html>
        </AuthProvider>
    );
}

const notoSansBengali = Noto_Sans_Bengali({
    variable: "--font-bengali",
    subsets: ["bengali"],
    weight: ["400", "500", "600", "700"],
    display: "swap",
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "A Unique EduTech App",
    description: "Generated by create next app",
};
